{% set version = "1.0.4" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-lifecycle
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/lifecycle_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lifecycle/lifecycle_{{ version }}.tar.gz
  sha256: ada4d3c7e84b0c93105e888647c5754219a8334f6e1f82d5afaf83d4855b91cc

build:
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli >=3.4.0
    - r-glue
    - r-rlang >=1.0.6
  run:
    - r-base
    - r-cli >=3.4.0
    - r-glue
    - r-rlang >=1.0.6

test:
  commands:
    - $R -e "library('lifecycle')"           # [not win]
    - "\"%R%\" -e \"library('lifecycle')\""  # [win]

about:
  home: https://github.com/r-lib/lifecycle
  license: MIT
  summary: Manage the life cycle of your exported functions with shared conventions, documentation badges, and non-invasive deprecation warnings. The 'lifecycle' package defines four development stages (experimental, maturing, stable, and questioning) and three deprecation stages (soft-deprecated, deprecated, and defunct).
    It makes it easy to insert badges corresponding to these stages in your documentation. Usage of deprecated functions are signalled with increasing levels of non-invasive verbosity.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: lifecycle
# Title: Manage the Life Cycle of your Package Functions
# Version: 0.1.0
# Authors@R:  c( person(given = "Lionel", family = "Henry", role = c("aut", "cre"), email = "lionel@rstudio.com"), person(given = "RStudio", role = "cph") )
# Description: Manage the life cycle of your exported functions with shared conventions, documentation badges, and non-invasive deprecation warnings. The 'lifecycle' package defines four development stages (experimental, maturing, stable, and questioning) and three deprecation stages (soft-deprecated, deprecated, and defunct). It makes it easy to insert badges corresponding to these stages in your documentation. Usage of deprecated functions are signalled with increasing levels of non-invasive verbosity.
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# Depends: R (>= 3.2)
# Imports: glue, rlang (>= 0.4.0)
# Suggests: covr, crayon, knitr, rmarkdown, testthat (>= 2.1.0)
# RoxygenNote: 6.1.1
# URL: https://github.com/r-lib/lifecycle
# BugReports: https://github.com/r-lib/lifecycle/issues
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-07-27 07:28:35 UTC; lionel
# Author: Lionel Henry [aut, cre], RStudio [cph]
# Maintainer: Lionel Henry <lionel@rstudio.com>
# Repository: CRAN
# Date/Publication: 2019-08-01 12:50:05 UTC
